### ISSUE TITLE
Make - arrêt à l'étape 5

### ISSUE THREAD

**Issue by cyphos1973** [EnMarche/en-marche.fr#1121]
Bonjour
Je suis sous ubuntu 16.04
Je me heurte au problème de make. Merci beaucoup d'avance de vos réponses
```
cyphos@LENOVO-X230:~/PROJETS/Symfony-enmarche$ docker -v
Docker version 1.12.6, build 78d1802

cyphos@LENOVO-X230:~/PROJETS/Symfony-enmarche$ docker-compose -v
docker-compose version 1.8.0, build unknown

cyphos@LENOVO-X230:~/PROJETS/Symfony-enmarche$ make -v
GNU Make 4.1
Construit pour i686-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>
Ceci est un logiciel libre : vous êtes autorisé à le modifier et à la redistribuer.
Il ne comporte AUCUNE GARANTIE, dans la mesure de ce que permet la loi.
```

quand je fais cette commande : `sudo make start`

```
Step 5 : RUN apt-get update -q &&     apt-get install -qy software-properties-common language-pack-en-base &&     export LC_ALL=en_US.UTF-8 &&     export LANG=en_US.UTF-8 &&     add-apt-repository ppa:ondrej/php &&     apt-get update -q &&     apt-get install --no-install-recommends -qy         ca-certificates         cron         curl         nano         vim         nginx         git         graphviz         mysql-client         php7.1         php7.1-bcmath         php7.1-common         php7.1-curl         php7.1-dom         php7.1-fpm         php7.1-gd         php7.1-iconv         php7.1-intl         php7.1-json         php7.1-mbstring         php7.1-mcrypt         php7.1-mysql         php7.1-pdo         php7.1-phar         php7.1-sqlite         php7.1-xdebug         php7.1-xml         php7.1-zip         supervisor         tzdata         wget &&     apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     cp /usr/share/zoneinfo/Europe/Paris /etc/localtime && echo "Europe/Paris" > /etc/timezone &&     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&     curl -L -o /tmp/nodejs.tar.gz https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz &&     tar xfvz /tmp/nodejs.tar.gz -C /usr/local --strip-components=1 &&     rm -f /tmp/nodejs.tar.gz &&     npm install yarn -g &&     mkdir /run/php
 ---> Running in ae92e5c66547
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x835c220, 0x975e0a80)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x97629974)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x2c1
panic(0x835c220, 0x975e0a80)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x976295fc, 0x97566588, 0x97629684)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xfd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x975945d0, 0x86bcfb50, 0x975e0a80)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x474
main.glob.func8(0x975c81e0, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x57
reflect.Value.call(0x8302700, 0x842f7c0, 0x13, 0x838d7b8, 0x4, 0x97629934, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0xeeb
reflect.Value.Call(0x8302700, 0x842f7c0, 0x13, 0x97629934, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0x8c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x8302700, 0x842f7c0, 0x975c81e0, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x25f
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x838fcd8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x840e120, 0x51, 0x0, ...)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xda7
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x975ba240, 0x97556070, 0x2, 0x2, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x92b
main.main()
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main.go:132 +0xa60
```

**Comment by mykiwi** [comment]
Bonjour @cyphos1973,

Desolé mais je n'ai pas réussi à reproduire ton problème:
```
# Testé sur play-with-docker.com
git clone https://github.com/EnMarche/en-marche.fr.git
cd en-marche
make start
```

**Comment by cyphos1973** [comment]
Bonjour
Oui, ça foncitonne sur ce site
et après ? je fais quoi?

**Comment by mykiwi** [comment]
Peux-tu essayer avec une version à jour de docker ?

**Comment by cyphos1973** [comment]
La version de docker sur ubuntu est la dernière : 1.12.6, build 78d1802

**Comment by tgalopin** [comment]
Est-ce que le problème est aussi présent en dehors de make?

**Comment by cyphos1973** [comment]
oui il me semble aussi
"docker run hello-world" pose aussi problème

**Comment by tgalopin** [comment]
Dans ce cas le problème semble venir de votre installation de Docker. Il vaudrait mieux vous tourner vers des ressources liées au support Docker, nous ne pourrons pas vous aider aussi bien qu'elles.

**Comment by cyphos1973** [comment]
après plus tests et vérification sur l'installation de Docker, finalement, docker s'installe uniquement sur 64bits et non 32bits. C'est bien dommage. Vous n'avez pas d'autres solutions que d'imposer docker?

**Comment by mykiwi** [comment]
Tu peux l'installer sans utiliser docker, il suffit de lire le [Dockerfile](https://github.com/EnMarche/en-marche.fr/blob/master/docker/dev/Dockerfile) et le [docker-compose](https://github.com/EnMarche/en-marche.fr/blob/master/docker-compose.yml) pour savoir quelles versions des logiciels ton PC a besoin d'avoir pour faire tourner le projet, puis d'adapter ton fichier `app/config/paramters.yml` en conséquence pour que PHP sache comment contacter redis, la base de donnee, ... Et pour finir, jouer les commandes du [Makfile](https://github.com/EnMarche/en-marche.fr/blob/master/Makefile) à la main (sans passer par docker).

**Comment by Stoakes** [comment]
Salut,

Est-ce que tu n'essaierais pas d'installer docker depuis les dépôts Ubuntu (ce n'est pas la méthode conseillée) au lieu de le faire depuis ceux de Docker ? 
Pour ma part je suis aussi sur Ubuntu 16.04, tout marche parfaitement, mais `docker -v` donne une sortie différente de la tienne :

```
$ docker --version
Docker version 17.03.1-ce, build c6d412e
```

[Voici mon script d'installation de docker et docker-compose](https://gist.github.com/Stoakes/a5adb36e9211964dbf00b47d36edd181).

**Comment by cyphos1973** [comment]
[https://store.docker.com/editions/community/docker-ce-server-ubuntu](url)
`To install Docker CE, you need the 64-bit version of one of these Ubuntu versions:`

**Comment by marineb** [comment]
@cyphos1973 are you still having issues ? closing this for now.
